"""PDF parsing sub-package."""

from .classifier import PDFCategory, PDFClassification, classify_pdf
from .classifier import detect_scanned_no_text, detect_scanned_with_text, detect_native_text
from .extractor import extract_text_dataframe, extract_images_dataframe, extract_full_with_style
from .tables import detect_fragmented_tables, pdf_to_excel

# Script unique parse_pdf — point d'entrée client
from .parse_pdf import (
    parse_pdf,
    apply_changes,
    inspect_pdf,
    classify_inspection,
    build_doc_summary,
    inspection_to_dataframes,
    PDFInspection,
    PageInfo,
    LineInfo,
    ImageInfo,
    TableInfo,
    CATEGORY_WORD_NATIVE,
    CATEGORY_DESIGN_TOOL,
    CATEGORY_SCANNED,
    CATEGORY_OTHER,
    PAGE_TYPE_NATIVE,
    PAGE_TYPE_NATIVE_WITH_IMAGE,
    PAGE_TYPE_SCANNED,
    PAGE_TYPE_SCANNED_OCR_GOOD,
    PAGE_TYPE_SCANNED_OCR_BAD,
    PAGE_TYPE_MIXED,
    PAGE_TYPE_EMPTY,
    PAGE_TYPE_UNKNOWN,
    STRATEGY_NATIVE,
    STRATEGY_OCR,
    STRATEGY_HYBRID,
    STRATEGY_SKIP,
)

# TOC sub-package — détection et extraction de tables des matières
from .toc import (
    EmptyPDFError,
    InvalidPDFError,
    PDFReadError,
    PageAnalysis,
    TocDetectionResult,
    add_dataframe_toc_to_pdf,
    clean_toc_df,
    detect_toc,
    export_toc_to_excel,
    export_toc_to_json,
    extract_native_toc,
    extract_native_toc_detailed,
    extract_text_from_first_pages,
    extract_toc_by_numbering,
    extract_toc_dotted,
    extract_toc_from_links,
    extract_toc_multiline,
    filter_pdfs_with_native_toc,
    get_pdf_page_count,
    has_native_toc,
    nest_toc,
    # LLM extraction — optionnel (TODO-TOC-005)
    extract_toc_with_gpt,
    find_toc_pages,
    extract_raw_toc_text,
)

__all__ = [
    # Legacy (à archiver, cf. task #6)
    "PDFCategory",
    "PDFClassification",
    "classify_pdf",
    "detect_scanned_no_text",
    "detect_scanned_with_text",
    "detect_native_text",
    "extract_text_dataframe",
    "extract_images_dataframe",
    "extract_full_with_style",
    "detect_fragmented_tables",
    "pdf_to_excel",
    # parse_pdf (script principal)
    "parse_pdf",
    "apply_changes",
    "inspect_pdf",
    "classify_inspection",
    "build_doc_summary",
    "inspection_to_dataframes",
    "PDFInspection",
    "PageInfo",
    "LineInfo",
    "ImageInfo",
    "TableInfo",
    "CATEGORY_WORD_NATIVE",
    "CATEGORY_DESIGN_TOOL",
    "CATEGORY_SCANNED",
    "CATEGORY_OTHER",
    "PAGE_TYPE_NATIVE",
    "PAGE_TYPE_NATIVE_WITH_IMAGE",
    "PAGE_TYPE_SCANNED",
    "PAGE_TYPE_SCANNED_OCR_GOOD",
    "PAGE_TYPE_SCANNED_OCR_BAD",
    "PAGE_TYPE_MIXED",
    "PAGE_TYPE_EMPTY",
    "PAGE_TYPE_UNKNOWN",
    "STRATEGY_NATIVE",
    "STRATEGY_OCR",
    "STRATEGY_HYBRID",
    "STRATEGY_SKIP",
    # TOC — détection heuristique
    "detect_toc",
    "TocDetectionResult",
    "PageAnalysis",
    "PDFReadError",
    "InvalidPDFError",
    "EmptyPDFError",
    "extract_text_from_first_pages",
    "score_page",
    "TOC_KEYWORDS",
    "has_toc_keyword",
    "find_dotted_leader_lines",
    "find_lines_ending_with_number",
    "find_hierarchical_structure",
    "calculate_short_line_density",
    # TOC — extraction native (signets)
    "has_native_toc",
    "extract_native_toc",
    "extract_native_toc_detailed",
    "clean_toc_df",
    "nest_toc",
    "export_toc_to_json",
    "export_toc_to_excel",
    "get_pdf_page_count",
    "filter_pdfs_with_native_toc",
    # TOC — extraction textuelle
    "extract_toc_dotted",
    "extract_toc_multiline",
    "extract_title_candidates",
    "group_numbered_titles",
    # TOC — extraction par liens
    "extract_toc_from_links",
    "extract_toc_by_numbering",
    # TOC — écriture de signets
    "add_dataframe_toc_to_pdf",
    # TOC — LLM fallback (optionnel, pip install 'docpipeline[llm]')
    "extract_toc_with_gpt",
    "find_toc_pages",
    "extract_raw_toc_text",
]
