"""PDF parsing sub-package."""

from .classifier import PDFCategory, PDFClassification, classify_pdf
from .classifier import detect_scanned_no_text, detect_scanned_with_text, detect_native_text
from .extractor import extract_text_dataframe, extract_images_dataframe, extract_full_with_style
from .tables import detect_fragmented_tables, pdf_to_excel

# Script unique parse_pdf — point d'entrée client
from .parse_pdf import (
    parse_pdf,
    apply_changes,
    inspect_pdf,
    classify_inspection,
    build_doc_summary,
    inspection_to_dataframes,
    PDFInspection,
    PageInfo,
    LineInfo,
    ImageInfo,
    TableInfo,
    CATEGORY_WORD_NATIVE,
    CATEGORY_DESIGN_TOOL,
    CATEGORY_SCANNED,
    CATEGORY_OTHER,
    PAGE_TYPE_NATIVE,
    PAGE_TYPE_NATIVE_WITH_IMAGE,
    PAGE_TYPE_SCANNED,
    PAGE_TYPE_SCANNED_OCR_GOOD,
    PAGE_TYPE_SCANNED_OCR_BAD,
    PAGE_TYPE_MIXED,
    PAGE_TYPE_EMPTY,
    PAGE_TYPE_UNKNOWN,
    STRATEGY_NATIVE,
    STRATEGY_OCR,
    STRATEGY_HYBRID,
    STRATEGY_SKIP,
)

__all__ = [
    # Legacy (à archiver, cf. task #6)
    "PDFCategory",
    "PDFClassification",
    "classify_pdf",
    "detect_scanned_no_text",
    "detect_scanned_with_text",
    "detect_native_text",
    "extract_text_dataframe",
    "extract_images_dataframe",
    "extract_full_with_style",
    "detect_fragmented_tables",
    "pdf_to_excel",
    # parse_pdf (script principal)
    "parse_pdf",
    "apply_changes",
    "inspect_pdf",
    "classify_inspection",
    "build_doc_summary",
    "inspection_to_dataframes",
    "PDFInspection",
    "PageInfo",
    "LineInfo",
    "ImageInfo",
    "TableInfo",
    "CATEGORY_WORD_NATIVE",
    "CATEGORY_DESIGN_TOOL",
    "CATEGORY_SCANNED",
    "CATEGORY_OTHER",
    "PAGE_TYPE_NATIVE",
    "PAGE_TYPE_NATIVE_WITH_IMAGE",
    "PAGE_TYPE_SCANNED",
    "PAGE_TYPE_SCANNED_OCR_GOOD",
    "PAGE_TYPE_SCANNED_OCR_BAD",
    "PAGE_TYPE_MIXED",
    "PAGE_TYPE_EMPTY",
    "PAGE_TYPE_UNKNOWN",
    "STRATEGY_NATIVE",
    "STRATEGY_OCR",
    "STRATEGY_HYBRID",
    "STRATEGY_SKIP",
]
